"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-05 04:37:10.544210
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=False)
    op.create_table('call_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('directory_number', sa.String(length=64), nullable=True),
    sa.Column('mos', sa.Float(), nullable=True),
    sa.Column('jitter_ms', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packets_lost', sa.Integer(), nullable=True),
    sa.Column('packets_sent', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=48), nullable=True),
    sa.Column('concealed_secs', sa.Integer(), nullable=True),
    sa.Column('severely_concealed_secs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_quality_device'), 'call_quality', ['device'], unique=False)
    op.create_index(op.f('ix_call_quality_leg_id'), 'call_quality', ['leg_id'], unique=False)
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_mgr_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('orig_leg_id', sa.Integer(), nullable=True),
    sa.Column('dest_leg_id', sa.Integer(), nullable=True),
    sa.Column('orig_device', sa.String(length=64), nullable=True),
    sa.Column('dest_device', sa.String(length=64), nullable=True),
    sa.Column('calling_number', sa.String(length=64), nullable=True),
    sa.Column('original_called', sa.String(length=64), nullable=True),
    sa.Column('final_called', sa.String(length=64), nullable=True),
    sa.Column('orig_ip', sa.String(length=64), nullable=True),
    sa.Column('dest_ip', sa.String(length=64), nullable=True),
    sa.Column('orig_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connect_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnect_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('orig_cause', sa.Integer(), nullable=True),
    sa.Column('dest_cause', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_call_id'), 'call_records', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_records_call_mgr_id'), 'call_records', ['call_mgr_id'], unique=False)
    op.create_index(op.f('ix_call_records_calling_number'), 'call_records', ['calling_number'], unique=False)
    op.create_index(op.f('ix_call_records_dest_device'), 'call_records', ['dest_device'], unique=False)
    op.create_index(op.f('ix_call_records_dest_leg_id'), 'call_records', ['dest_leg_id'], unique=False)
    op.create_index(op.f('ix_call_records_final_called'), 'call_records', ['final_called'], unique=False)
    op.create_index(op.f('ix_call_records_orig_device'), 'call_records', ['orig_device'], unique=False)
    op.create_index(op.f('ix_call_records_orig_leg_id'), 'call_records', ['orig_leg_id'], unique=False)
    op.create_index(op.f('ix_call_records_orig_time'), 'call_records', ['orig_time'], unique=False)
    op.create_table('call_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=64), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('inbound_calls', sa.Integer(), nullable=False),
    sa.Column('outbound_calls', sa.Integer(), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=False),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mos_sum', sa.Float(), nullable=False),
    sa.Column('mos_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name', name='uq_call_stats_device_name')
    )
    op.create_index(op.f('ix_call_stats_device_name'), 'call_stats', ['device_name'], unique=False)
    op.create_table('catalog_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=16), nullable=False),
    sa.Column('poe_class', sa.Integer(), nullable=True),
    sa.Column('lifecycle', sa.String(length=32), nullable=True),
    sa.Column('replacement', sa.String(length=32), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key', name='uq_catalog_overrides_model_key')
    )
    op.create_index(op.f('ix_catalog_overrides_model_key'), 'catalog_overrides', ['model_key'], unique=False)
    op.create_table('cert_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ports', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', name='uq_cert_targets_host')
    )
    op.create_index(op.f('ix_cert_targets_host'), 'cert_targets', ['host'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('subject_cn', sa.String(length=255), nullable=True),
    sa.Column('issuer_cn', sa.String(length=255), nullable=True),
    sa.Column('self_signed', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('san', sa.Text(), nullable=True),
    sa.Column('serial', sa.String(length=80), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'port', name='uq_certificates_host_port')
    )
    op.create_index(op.f('ix_certificates_host'), 'certificates', ['host'], unique=False)
    op.create_table('cluster_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('registered_devices', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster', 'name', name='uq_cluster_nodes_cluster_name')
    )
    op.create_index(op.f('ix_cluster_nodes_cluster'), 'cluster_nodes', ['cluster'], unique=False)
    op.create_index(op.f('ix_cluster_nodes_name'), 'cluster_nodes', ['name'], unique=False)
    op.create_table('cluster_test_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('nodes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_test_logs_cluster_id'), 'cluster_test_logs', ['cluster_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('axl_host', sa.String(length=255), nullable=False),
    sa.Column('cucm_user', sa.String(length=128), nullable=False),
    sa.Column('cucm_password', sa.String(length=255), nullable=False),
    sa.Column('axl_version', sa.String(length=16), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('phone_web_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_clusters_name')
    )
    op.create_table('location_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('pattern', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_rules_location_id'), 'location_rules', ['location_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=64), nullable=False),
    sa.Column('registration_status', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('switch_name', sa.String(length=128), nullable=True),
    sa.Column('switch_port', sa.String(length=64), nullable=True),
    sa.Column('active_load', sa.String(length=128), nullable=True),
    sa.Column('has_serial', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_snapshots_device_name'), 'phone_snapshots', ['device_name'], unique=False)
    op.create_index(op.f('ix_phone_snapshots_sync_run_id'), 'phone_snapshots', ['sync_run_id'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=64), nullable=False),
    sa.Column('pkid', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('model_raw', sa.String(length=128), nullable=True),
    sa.Column('model_key', sa.String(length=16), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('device_pool', sa.String(length=128), nullable=True),
    sa.Column('site', sa.String(length=128), nullable=True),
    sa.Column('cluster', sa.String(length=64), nullable=True),
    sa.Column('configured_load', sa.String(length=128), nullable=True),
    sa.Column('directory_number', sa.String(length=64), nullable=True),
    sa.Column('registration_status', sa.String(length=32), nullable=True),
    sa.Column('status_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('active_load', sa.String(length=128), nullable=True),
    sa.Column('cm_node', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('hardware_revision', sa.String(length=64), nullable=True),
    sa.Column('switch_name', sa.String(length=128), nullable=True),
    sa.Column('switch_port', sa.String(length=64), nullable=True),
    sa.Column('switch_ip', sa.String(length=64), nullable=True),
    sa.Column('vlan_id', sa.String(length=16), nullable=True),
    sa.Column('web_reachable', sa.Boolean(), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=True),
    sa.Column('generation', sa.String(length=32), nullable=True),
    sa.Column('lifecycle', sa.String(length=32), nullable=True),
    sa.Column('poe_class', sa.Integer(), nullable=True),
    sa.Column('poe_watts', sa.Float(), nullable=True),
    sa.Column('replacement_key', sa.String(length=16), nullable=True),
    sa.Column('replacement_name', sa.String(length=128), nullable=True),
    sa.Column('replacement_poe_watts', sa.Float(), nullable=True),
    sa.Column('swap_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name', name='uq_phones_device_name')
    )
    op.create_index(op.f('ix_phones_cluster'), 'phones', ['cluster'], unique=False)
    op.create_index(op.f('ix_phones_device_name'), 'phones', ['device_name'], unique=False)
    op.create_index(op.f('ix_phones_device_pool'), 'phones', ['device_pool'], unique=False)
    op.create_index(op.f('ix_phones_directory_number'), 'phones', ['directory_number'], unique=False)
    op.create_index(op.f('ix_phones_generation'), 'phones', ['generation'], unique=False)
    op.create_index(op.f('ix_phones_ip_address'), 'phones', ['ip_address'], unique=False)
    op.create_index(op.f('ix_phones_lifecycle'), 'phones', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_phones_model_key'), 'phones', ['model_key'], unique=False)
    op.create_index(op.f('ix_phones_registration_status'), 'phones', ['registration_status'], unique=False)
    op.create_index(op.f('ix_phones_replacement_key'), 'phones', ['replacement_key'], unique=False)
    op.create_index(op.f('ix_phones_serial_number'), 'phones', ['serial_number'], unique=False)
    op.create_index(op.f('ix_phones_site'), 'phones', ['site'], unique=False)
    op.create_index(op.f('ix_phones_swap_status'), 'phones', ['swap_status'], unique=False)
    op.create_index(op.f('ix_phones_switch_name'), 'phones', ['switch_name'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_settings_key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_table('switch_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('available_watts', sa.Float(), nullable=True),
    sa.Column('used_watts', sa.Float(), nullable=True),
    sa.Column('polled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_name', name='uq_switch_polls_switch_name')
    )
    op.create_index(op.f('ix_switch_polls_switch_name'), 'switch_polls', ['switch_name'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('axl_count', sa.Integer(), nullable=False),
    sa.Column('ris_count', sa.Integer(), nullable=False),
    sa.Column('web_count', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trunk_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_name', sa.String(length=128), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_name', name='uq_trunk_capacity_gateway')
    )
    op.create_index(op.f('ix_trunk_capacity_gateway_name'), 'trunk_capacity', ['gateway_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('events', sa.String(length=255), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trunk_capacity_gateway_name'), table_name='trunk_capacity')
    op.drop_table('trunk_capacity')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_switch_polls_switch_name'), table_name='switch_polls')
    op.drop_table('switch_polls')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_phones_switch_name'), table_name='phones')
    op.drop_index(op.f('ix_phones_swap_status'), table_name='phones')
    op.drop_index(op.f('ix_phones_site'), table_name='phones')
    op.drop_index(op.f('ix_phones_serial_number'), table_name='phones')
    op.drop_index(op.f('ix_phones_replacement_key'), table_name='phones')
    op.drop_index(op.f('ix_phones_registration_status'), table_name='phones')
    op.drop_index(op.f('ix_phones_model_key'), table_name='phones')
    op.drop_index(op.f('ix_phones_lifecycle'), table_name='phones')
    op.drop_index(op.f('ix_phones_ip_address'), table_name='phones')
    op.drop_index(op.f('ix_phones_generation'), table_name='phones')
    op.drop_index(op.f('ix_phones_directory_number'), table_name='phones')
    op.drop_index(op.f('ix_phones_device_pool'), table_name='phones')
    op.drop_index(op.f('ix_phones_device_name'), table_name='phones')
    op.drop_index(op.f('ix_phones_cluster'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_phone_snapshots_sync_run_id'), table_name='phone_snapshots')
    op.drop_index(op.f('ix_phone_snapshots_device_name'), table_name='phone_snapshots')
    op.drop_table('phone_snapshots')
    op.drop_table('locations')
    op.drop_index(op.f('ix_location_rules_location_id'), table_name='location_rules')
    op.drop_table('location_rules')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_cluster_test_logs_cluster_id'), table_name='cluster_test_logs')
    op.drop_table('cluster_test_logs')
    op.drop_index(op.f('ix_cluster_nodes_name'), table_name='cluster_nodes')
    op.drop_index(op.f('ix_cluster_nodes_cluster'), table_name='cluster_nodes')
    op.drop_table('cluster_nodes')
    op.drop_index(op.f('ix_certificates_host'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_cert_targets_host'), table_name='cert_targets')
    op.drop_table('cert_targets')
    op.drop_index(op.f('ix_catalog_overrides_model_key'), table_name='catalog_overrides')
    op.drop_table('catalog_overrides')
    op.drop_index(op.f('ix_call_stats_device_name'), table_name='call_stats')
    op.drop_table('call_stats')
    op.drop_index(op.f('ix_call_records_orig_time'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_orig_leg_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_orig_device'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_final_called'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_dest_leg_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_dest_device'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_calling_number'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_call_mgr_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_call_id'), table_name='call_records')
    op.drop_table('call_records')
    op.drop_index(op.f('ix_call_quality_leg_id'), table_name='call_quality')
    op.drop_index(op.f('ix_call_quality_device'), table_name='call_quality')
    op.drop_table('call_quality')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
